// import Head from "next/head";
// import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import styles1 from "../styles/Home1.module.css";
import styles2 from "../styles/Home2.module.css";
import Dummy from "../components/dummyStyledJsx";

export default function Home() {
  // console.log("styles", styles);
  // console.log("styles1", styles1);
  // console.log("styles2", styles2);
  return (
    <div className={styles.container}>
      <style jsx>
        {`
          .home {
            border-radius: 5px;
          }
        `}
      </style>
      {/* <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <Link rel="icon" href="/favicon.ico" />
      </Head> */}

      <main className={styles.main}>
        {/* commented as Image component doesn't work with SSG */}
        {/* <Image
          className={styles.homeImg}
          src="/coder.png"
          alt="home"
          width={237}
          height={158}
        /> */}

        <div className={styles.imageWrap}>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            className={styles.homeImg}
            src="/coder.png"
            alt="home"
            width={237}
            height={158}
          />
        </div>

        <h2 className={styles.title}>
          <span>&lt;Hunting Coder /&gt;</span>
        </h2>

        {/* eg. for styled jsx */}
        {/* <Dummy /> */}
        {/* <p className="dummy">Test dummy css</p> */}
        <article>
          {/* eg. for css modules */}
          {/* <div>
            <h5 className={styles1.color}>Title</h5>
            <p className={styles2.bgColor}>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo
            </p>
          </div> */}
          <h2 className={styles.h2}>Latest Blogs</h2>
          <div className="blogItem">
            <h3>How to learn Javascript in 2o24</h3>
            <p>
              Javascript is a langauge used to wirte frontend of an application.
            </p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div className="blogItem">
            <h3>How to learn NextJs in 2o24</h3>
            <p>
              NesxtJs is a langauge used to wirte frontend of an application.
            </p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div className="blogItem">
            <h3>How to learn ReactJS in 2o24</h3>
            <p>
              ReactJs is a langauge used to wirte frontend of an application.
            </p>
            <button className={styles.btn}>Read More</button>
          </div>
        </article>
      </main>
    </div>
  );
}
